### PR TITLE
Rest service tests

### PR DESCRIPTION
**Pull request by proehlen**
@ClemensLey I've added the tests based on the code you sent me.   To support this:

- I've made the db connection values use environment variables so I can run the tests on a different database and not destroy data in my main db.
- I've split the app out of index.js so that it can be imported into the jest test suite and the server shut down at the end of the test.

This pull request has an outstanding issue.  After the tests successfully run, jest reports this message:

> Jest did not exit one second after the test run has completed.
> index.js:338
> This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

It shuts down automatically after a second or two.  I've tried following the advice above and can't see the reason for it.  Maybe the express callback in `afterAll` is returning before the server is fully dead.  I'll do some more debugging but creating this pull request in the mean time in case you have feedback on the changes.

### CODE REVIEW

**Comment by ClemensLey** [comment]
@proehlen First of all: awesome that you added these test cases!

I get the same error. I think the problem is that the server that is set up in the beforeAll of app.test.js is still running when all the tests terminate.

While I do not know how to fix this, I know a workaround: you can remove the beforeAll and afterAll in app.test.js. Then when you want to run the test you need to run 'npm run serve' in a second terminal beforehand. If I do it this way it works for me.

Good move to use dotenv instead of hardcoded values as well!

**Comment by proehlen** [comment]
Hi @ClemensLey Thanks for the review; I've incorporated your changes.  I've made the app port an env var to support running tests against the test server/database (running in another shell) and not destroy data in the main database.   Let me know if you've got any further suggestions or changes.

**Comment by ClemensLey** [comment]
Hi @proehlen. I am having trouble with dotenv. I've created a .env file in the root folder with the following content:

```
PORT=3000
PGUSER=clemensley
PGPASSWORD=
PGHOST=localhost
PGPORT=5432
PGDATABASE=unp2sh
```

When I run the app I get the log "Un-P2SH listening on port undefined" which probably means that rocess.env.PORT is not defined. Do you know what I might be doing wrong?

**Comment by proehlen** [comment]
Hi @ClemensLey - sorry I should have picked up on your earlier mention of dotenv.  I wasn't actually using  that package but instead setting a parameter in my IDE to load different .env files for different purposes (test vs run serve).  I've now added dotenv.  The package documentation explicitly recommends against using different `.env` files in the one environment (see [link](https://github.com/motdotla/dotenv#should-i-have-multiple-env-files)).  I've played with various options and I can't figure out how to make two servers work with the one file so I've (temporarily at least) bailed on the concept of having a separate database for destructive tests.  If database preservation is important then I guess I developers can set up another enviornment / copy of the project with a different  `.env` file.

Anyway, sorry this has been more drawn out than I expected it to be.  Cheers.

**Comment by ClemensLey** [comment]
Hi @proehlen. I see that explains it. Works perfectly now, awesome work. Merging now...

**Pull request merged**
